version: '3.9'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${BACKEND_DATABASE_ROOT_USERNAME}
      POSTGRES_PASSWORD: ${BACKEND_DATABASE_ROOT_PASSWORD}
      POSTGRES_DB: ${BACKEND_DATABASE_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  front-end:
    build: ./front-end
    restart: unless-stopped
    env_file:
      - ./front-end/.env

  back-end:
    build: ./back-end
    restart: unless-stopped
    env_file:
      - ./back-end/.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./back-end/uploads:/app/uploads
    depends_on:
      - db

volumes:
  db_data:
